### ISSUE TITLE
 PrometheusExporter's HTTP Sanity Check breaks valid configuration 

### ISSUE THREAD

**Issue by dmcgiv** [open-telemetry/opentelemetry-dotnet#2881] opened 2022-02-09 21:13 UTC
# Bug Report

Impacted NuGet package

- OpenTelemetry.Exporter.Prometheus 1.2.0-rc2

Runtime version 

- net461

## Symptom
#2771 introduced validation in PrometheusExporterOptions.HttpListenerPrefixes setter which does not accept valid wildcard hostname e.g. http://+:9184/ 

see documentation which confirms this is valid https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistenerprefixcollection.add?view=netframework-4.6.1#remarks 

**What is the expected behavior?**

No validation exception and the HTTP Listener server request for any hostname associated with the server on the given port on .

**What is the actual behavior?**

ArgumentException("Prometheus server path should be a valid URI with http/https scheme.")

**Comment by Yun-Ting** [comment] 2022-02-09 21:54
I'll be working on the fix.

**Comment by 8** [comment] 2022-04-05 15:58
Duplicate of #2840

**Closed** 2022-08-02 18:55 UTC
Labels: bug, area:exporter:prometheus, area:exporter
