### ISSUE TITLE
Add support for GRPC RPC Metrics

### ISSUE THREAD

**Issue by lindeberg** [open-telemetry/opentelemetry-dotnet#5202] opened 2024-01-04 14:57 UTC
# Feature Request

I want to be able to instrument [RPC Metrics](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-metrics.md) from `Grpc.AspNetCore`.

**Describe the solution you'd like:**
`.AddGrpcInstrumentation()`

**Comment by cijothomas** [comment] 2024-01-17 19:56
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2555 Closing as duplicate of this.

**Closed by cijothomas** 2024-01-17 19:56 UTC
Labels: enhancement, area:instrumentation
