### ISSUE TITLE
asp.net core metrics middleware and non httplistener 

### ISSUE THREAD

**Issue by simon-davis** [open-telemetry/opentelemetry-dotnet#534] opened 2020-03-10 15:59 UTC
Hi,

I am currently implementing metrics into a POC and wondering if there are any future plans to provide any metric middleware for .net core request instrumentation and an exporter (One that does not rely on httplistener)?

We currently use packages such as appmetrics and prometheus-net for these purposes if it helps for context of what I mean!

**Comment by MikeGoldsmith** [comment] 2020-03-10 16:44
Hi @simon-davis 

Yes, there has been discussion on exposing exporters as Middleware in ASP.NET core. The work to decouple the PrometheusExporter was a step towards that; @cijothomas said he might look at it soon but we're also very open to additional contributions.

**Comment by cijothomas** [comment] 2020-03-10 16:56
Duplicate of: https://github.com/open-telemetry/opentelemetry-dotnet/issues/65
Its tagged as P1, so we'll get to it after all P0 item are complete.

I believe @hananiel also mentioned interest in this area.

**Closed** 2020-03-10 17:05 UTC
