### ISSUE TITLE
Activities not mapping to the expected parents

### ISSUE THREAD

**Issue by cabadam** [open-telemetry/opentelemetry-dotnet#2079] opened 2021-06-11 20:03 UTC
# Question

**Describe your environment.**

I have a WPF application (.NET Framework 4.7.1) to which we are exploring adding telemetry.  This application uses HttpClient to send various web requests to a WebAPI backend.  Eventually, this will expand to include the backend as well, but for now, we are just looking at the UI client.

**What are you trying to achieve?**

All of our web calls ultimately funnel through a single async method which is where we are calling startActivity.  Inside that, it then calls HttpClient.PostAsync.  We have the data transmitting to a Jaeger instance.  What we expected to see is that our explicitly created "startActivity" calls there would be top level items and the activities generated by httpclient would then appear inside it.

However, what we are finding seems Very Random(TM).  Sometimes our activity is a top level item, sometimes the HttpClient item is top level.  Sometimes our activities have other "our activities" nested under them (which conceptually is not the case).  In fact, I have yet to find a case where it worked "correctly" (based on expectation one of our activities had its one HTTP call within it and nothing else).

This async method I referred to is called from a number of different threads and these web calls will certainly overlap. It almost feels like the OpenTelemetry framework is not consistently picking up the correct parent activity because of this?

## Additional Context

Example code is below that spins up 20 parallel calls to the HttpClient, each wrapped in a manually created activity, named with the numbers 1-20.

What i expected to see was 1-20 are all top level items in Jaeger, with 1 subitem on each for the HTTP call.  Instead, many top level items no sub items, and some subitems have multiple.  For example, in this screenshot, number 11 happened to get a bunch of the HTTP calls (but not all):
![image](https://user-images.githubusercontent.com/11012233/121742889-15064580-cac6-11eb-8eaa-870050d10fd0.png)

![image](https://user-images.githubusercontent.com/11012233/121742759-e7210100-cac5-11eb-941c-f12e6e00b9a1.png)

```csharp
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Threading.Tasks;
using OpenTelemetry;
using OpenTelemetry.Trace;

namespace ConsoleApp3
{
    class Program
    {
        static ActivitySource activitySource = new ActivitySource(Assembly.GetExecutingAssembly().GetName().Name, Assembly.GetExecutingAssembly().GetName().Version.ToString());

        private static HttpClient client = new HttpClient();

        static void Main(string[] args)
        {
            using var tracerProvider = Sdk.CreateTracerProviderBuilder()
                .AddSource(Assembly.GetExecutingAssembly().GetName().Name)
                .AddHttpClientInstrumentation()
                .AddJaegerExporter()
                .Build();
            
            Task.WaitAll(Enumerable.Range(1, 20).Select(MakeWebCall).ToArray());
        }

        private static async Task MakeWebCall(int id)
        {
            using var activity = activitySource.StartActivity(id.ToString(), ActivityKind.Client);
            using HttpResponseMessage msg = await client.PostAsync($"http://localhost/{id}", new StringContent("dummy data")).ConfigureAwait(false);
        }
    }
}
```

**Comment by cabadam** [comment] 2021-06-11 21:29
I did confirm this problem was not unique the Jaeger exporter.  I added the Console exporter to do a run, and found that it showed similar behavior.  Doing a text search on the console output for one of the activity (span) IDs that showed many children showed the same:

> 	Line 2: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 39: Activity.Id:          00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 48: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 86: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 132: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 178: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 224: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 270: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 316: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 347: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 370: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 393: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 416: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01
> 	Line 439: Activity.ParentId:    00-e828c3fa0357a441bc22336dc211cd7d-79cb74853f766048-01

**Comment by cijothomas** [comment] 2021-06-11 21:32
Weired! I tried this and not reproing! I tried console, jaeger and zipkin. See sample from zipkin below. Jaeger also same.
![image](https://user-images.githubusercontent.com/5232798/121750704-bccd4480-cac1-11eb-8ee9-a426d34fbab8.png)

I modifed the examples app to match yours:
```
namespace Examples.Console
{
    internal class TestHttpClient
    {
        internal static ActivitySource Source = new ActivitySource("http-client-test");
        internal static HttpClient Client = new HttpClient();


    // To run this example, run the following command from
    // the reporoot\examples\Console\.
    // (eg: C:\repos\opentelemetry-dotnet\examples\Console\)
    //
    // dotnet run httpclient
    internal static object Run()
        {
            System.Console.WriteLine("Hello World!");

            using var openTelemetry = Sdk.CreateTracerProviderBuilder()
                .AddHttpClientInstrumentation()
                .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("http-service-example"))
                .AddSource("http-client-test")
                .AddConsoleExporter()
                .AddJaegerExporter()
                .Build();

            Task.WaitAll(Enumerable.Range(1, 20).Select(MakeWebCall).ToArray());
            System.Console.WriteLine("Press Enter key to exit.");

            return null;
        }

        private static async Task MakeWebCall(int id)
        {
            using var activity = Source.StartActivity(id.ToString(), ActivityKind.Client);
            using HttpResponseMessage msg = await Client.PostAsync($"https://httpbin.org/post", new StringContent("dummy data" + id)).ConfigureAwait(false);
        }
    }
}
```

**Comment by cijothomas** [comment] 2021-06-11 21:34
Could you target .netcore3.1 and see if it reproes.

**Comment by cabadam** [comment] 2021-06-11 21:57
Sure, this was on .NET Framework 4.7.1 (like our production app), but I'll try that too.

**Comment by cabadam** [comment] 2021-06-11 22:06
That does in fact seem to be the difference.  The same code and NuGet references results in the expected before against .NET Core.

I pushed my sample app to: https://github.com/cabadam/http-request-opentelemetry
master branch is the .NET Framework 4.7.1 app that exhibits the issue (for me).
netcore branch is the same thing, but project file changed to .NET Core 3.1.

**Comment by cijothomas** [comment] 2021-06-11 22:10
Thanks. It confirmed what I suspected ! There is an issue which was earlier investigated and confirmed in the .NET runtime repo. I'll find the tracking issue and workarounds.

**Comment by cabadam** [comment] 2021-06-12 00:51
Great, sounds good.  I had tried to search around, but came up empty.  Thanks for taking a look!

**Comment by cabadam** [comment] 2021-06-22 02:10
> Thanks. It confirmed what I suspected ! There is an issue which was earlier investigated and confirmed in the .NET runtime repo. I'll find the tracking issue and workarounds.

Were you ever able to track down a workaround for this?  Thanks!

**Comment by cabadam** [comment] 2021-07-13 15:15
@cijothomas Just pinging you again to see if you had any more information.  We've continued implementing this across our application, but are unfortunately still seeing this behavior.
Thanks

**Comment by toddfoust** [comment] 2021-07-14 00:15
Hello @cabadam Cijo asked me to respond because we recently worked with another customer facing same issue where telemetry was getting 'mislabeled' operation ids. 

This is due to an issue somewhere in System.Diagnostics.DiagnosticSource namespace around code written to support Activities for the older desktop framework versions.  We've seen scenarios where the wrong Activity object will get assigned to the wrong async thread, and so you'd see some telemetry items get set with the wrong distributed telemetry operation id. 

This problem impacts Application Insights, Open Telemetry or any [Diagnostic Listener](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.diagnosticlistener?view=net-5.0) implementation that is running on .NET 4.x frameworks. The injected diagnostic listeners don't account for the behavior within .NET 4.x where the framework might chain calls out to the same URI on the same connection in a singular async context. 

If you move the code over to .NET Core 3.1 or .NET 5.0 or later then you will avoid this problem. This only impacts 4.x apps.

One of our software architects came up with a workaround by supplying a custom HttpHandler to the HttpClient which will 
1. Try to pick a free connection
2. Creates a new one if under limit
3. More advanced stuff (least busy algorithm) should we exhaust available connections


``` csharp
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using System.Runtime.CompilerServices;
using System.IO;

namespace FullFramework
{
    public class QueueHttpHandler : DelegatingHandler
    {
        // We store a mapping from service point to semaphore slim. This lets us properly limit concurrent requests for individual URLs
        // based on the mapping from URI (service point) to semaphore slim.
        private ConditionalWeakTable<ServicePoint, SemaphoreSlim> _servicePointMap = new ConditionalWeakTable<ServicePoint, SemaphoreSlim>();

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var servicePoint = ServicePointManager.FindServicePoint(request.RequestUri);

            // This assumes HTTP/1.1, one request per connection (which is the case by default anyways)
            var queue = _servicePointMap.GetValue(servicePoint, sp => new SemaphoreSlim(sp.ConnectionLimit, sp.ConnectionLimit));

            await queue.WaitAsync();
            try
            {
                var response = await base.SendAsync(request, cancellationToken);
                response.Content = new QueueContent(response.Content, queue);
                return response;
            }
            catch
            {
                // If there's an exception producing the response, release the semaphore slim
                queue.Release();
                throw;
            }
        }

        // This content is responsible releasing the semaphore when the content is fully read
        private class QueueContent : HttpContent
        {
            private readonly HttpContent _httpContent;
            private readonly SemaphoreSlim _queue;

            public QueueContent(HttpContent httpContent, SemaphoreSlim queue)
            {
                _httpContent = httpContent;
                _queue = queue;
            }

            protected override async Task SerializeToStreamAsync(Stream stream, TransportContext context)
            {
                try
                {
                    await _httpContent.CopyToAsync(stream, context);
                }
                finally
                {
                    // Release the semaphore slim after the copy
                    _queue.Release();
                }
            }

            protected override bool TryComputeLength(out long length)
            {
                
                var contentLength = _httpContent.Headers.ContentLength;
                if (contentLength == null)
                {
                    length = 0;
                    return false;
                }

                length = contentLength.Value;
                return true;
            }
        }
    }
}

```

I think you'll be able to pass this custom handler, QueueHttpHandler, directly into your [HttpClient constructor](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.-ctor?view=net-5.0#System_Net_Http_HttpClient__ctor_System_Net_Http_HttpMessageHandler_).

If you are doing dependency injection, like our earlier customer, then something like this will help configure the handler too: 

``` csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<QueueHttpHandler>();
            services.AddHttpClient<TestClient1>().AddHttpMessageHandler<QueueHttpHandler>();
            ....
```

Hope this helps. Let us know if the workaround works for you too. We tested it out earlier and saw the workaround hold up really well under load.

**Comment by cabadam** [comment] 2021-07-14 23:15
Todd, thanks a lot for the update.  That information looks great.  I've passed this on to our team to give a try.

**Closed** 2021-07-27 19:10 UTC
Labels: question
