### ISSUE TITLE
Nuget readme

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2977] opened 2022-03-07 02:36 UTC
Modify nuget to include readme. I think we can put the readme.md file under each project, or simply point to it.
https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org

**Comment by stevejgordon** [comment] 2024-07-08 16:05
@cijothomas / @martinjt - Dupe of #4895 and can be closed.

**Closed** 2024-07-08 17:02 UTC
Labels: enhancement, infra
