### ISSUE TITLE
Minimal API trace missing `http.route` tag

### ISSUE THREAD

**Issue by andreasuvoss** [open-telemetry/opentelemetry-dotnet#4192] opened 2023-02-15 05:30 UTC
# Bug Report

Packages used:

* `OpenTelemetry.Exporter.Console 1.4.0-rc.4`
* `OpenTelemetry.Extensions.Hosting 1.4.0-rc.4`
* `OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.13`

Runtime versions:

* `net6.0`
* `net7.0`

## Symptom

The resulting trace from calling an endpoint mapped using Minimal Api does not contain the `http.route` tag, however the tag is present when calling an endpoint defined in a classic controller.

**What is the expected behavior?**

The trace contains the tag `http.route` for endpoints created with the Minimal API syntax.

```
Activity.Tags:
    ....
    http.route: works/{id:int}
    ....
```

**What is the actual behavior?**

The trace does not contain the `http.route` tag for endpoints created with the Minimal API syntax.

## Reproduce

With the code below call endpoint `/does-not-work/1234` and observe that `http.route` is not present among the tags in the console output. Do the same for `/works/1234` and observe that the `http.route` tag is present among the tags in the console output.

```csharp
using Microsoft.AspNetCore.Mvc;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

builder.Services.AddOpenTelemetry().WithTracing(b =>
{
    var resourceBuilder = ResourceBuilder.CreateDefault()
        .AddService("MinimalExample", null, "0.0.1");
    b.SetResourceBuilder(resourceBuilder)
        .AddAspNetCoreInstrumentation()
        .AddConsoleExporter();
});

var app = builder.Build();

app.MapControllers();

app.MapGet("/does-not-work/{id:int}", (int id) => "Trace without http.route");

app.Run();

[ApiController]
public class TestController : ControllerBase
{
    [HttpGet]
    [Route("/works/{id:int}")]
    public IActionResult GetTest(int id)
    {
        return Ok();
    }
}
```
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-rc.4" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.4.0-rc.4" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.13" />
    </ItemGroup>
</Project>
```
## Additional Context

I have looked a bit into the source of `OpenTelemetry.Instrumentation.AspNetCore` and it seems like the `OnMvcBeforeActionEvent` never occurs when calling the endpoint created with Minimap API syntax. All other expected tags seem to be present.

The issue seems to be the same with both `net6.0` and `net7.0`.

**Comment by vishweshbankwar** [comment] 2023-02-17 21:11
Thanks for reporting. The issue is already being tracked with https://github.com/open-telemetry/opentelemetry-dotnet/issues/3461. Closing this one.

**Closed by vishweshbankwar** 2023-02-17 21:11 UTC
Labels: bug
