### ISSUE TITLE
Logs are experimental

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-dotnet#1811] opened 2021-02-08 18:38 UTC
Currently it seems that logs are published in the 1.0 release https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry/Logs

**Comment by neoaisac** [comment] 2021-04-23 10:26
Sorry, does this mean that Logs should also be marked as experimental in the README, as it happens with the metrics? Or does this mean that they should not have been published at all?

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/README.md

**Comment by RehanSaeed** [comment] 2021-04-23 10:49
Logs don't currently work out of the box without additional code.

I think this issue is a duplicate of https://github.com/open-telemetry/opentelemetry-dotnet/issues/1739.

**Closed** 2023-06-06 19:12 UTC
Labels: bug
