### ISSUE TITLE
Prometheus Exporter should allow for wildcard URL

### ISSUE THREAD

**Issue by doppleware** [open-telemetry/opentelemetry-dotnet#2886] opened 2022-02-11 07:20 UTC
# Bug Report

 OpenTelemetry.Exporter.Prometheus                      1.2.0-rc2   1.2.0-rc2

net 6.0

## Symptom

A validation error is thrown when trying to use HTTP Listener Prefix with wildcard when configuring the exporter.
For example:
options.HttpListenerPrefixes = new string[] { $"http://localhost:9091/",
            $"http://127.0.0.1:9091/", $"http://+:9091/", $"http://*:9091/"};

Would fail 

**What is the expected behavior?**

Allow wildcard in URL to be passed to HTTP listener. 

**What is the actual behavior?**

The exception is thrown that URL is not valid.

**Comment by dmcgiv** [comment] 2022-02-14 00:36
Duplicate of #2881

**Closed** 2022-02-17 07:29 UTC
Labels: bug
