### ISSUE TITLE
Dependency on Microsoft.Extensions.* 3.1.0 breaks applications on .NET Framework

### ISSUE THREAD

**Issue by spashaieva** [open-telemetry/opentelemetry-dotnet#4335] opened 2023-03-27 11:57 UTC
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry 1.4.0

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net472

## Symptom

Many services, which are using ASP.NET Core 2 on .NET Framework, are not able to onboard to OpenTelemetry and other packages such as OpenTelemetry.Extensions.Hosting because of dependency on Microsoft.Extensions.Logging.Configuration, Microsoft.Extensions.Logging and other extensions of version 3.1.0. 

.NET Platform Extensions v.2 are officially supported on .NET Framework ([ASP.NET Core 2.1 Packages (microsoft.com)](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet/2.1-packages)), and many existing .NET libraries that support .netstandard2.0 are built around version 2.x. Usage of version 3.1 breaks the integration with those libraries due to breaking changes and causes dependency hell.

**What is the expected behavior?**

OpenTelemetry and other related packages will be compatible with ASP.NET Core 2 and Microsoft.Extensions.* version 2.x.

**What is the actual behavior?**

Those packages bring dependency on newer version of Microsoft.Extensions that is 3.1.0, which leads to incompatibility with other modules of a service, which are relying on Extensions v.2.2.

## Reproduce
Here is a simple example how to reproduce this issue:
* Create project that targets .NET Framework 4.7.2.
* Reference package which depends on Microsoft.Extensions.Logging.Abstractions 2.2.0 for .netstandard2.0 and uses such types as `NullScope`, `FormattedLogValues` or else in a logger.
* Add package reference to OpenTelemetry 1.4.0.
* Use logger.
As a result, exception about type loading will occur, because OpenTelemetry depends on newer version of Microsoft.Extensions.Logging.Abstractions where several breaking changes were introduced (e.g., NullScope removal).

**Comment by cijothomas** [comment] 2023-03-27 16:16
Closing as duplicate of https://github.com/open-telemetry/opentelemetry-dotnet/issues/4126

**Closed by cijothomas** 2023-03-27 16:16 UTC
Labels: bug
