### ISSUE TITLE
Ability to forget and reclaim MetricPoint (Delta)

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2360] opened 2021-09-17 00:01 UTC
Each Metric keeps track of its MetricPoints. This points are never removed, even if there are no new updates to it.
For delta aggregation:
We should reclaim any un-used MetricPoints, when we hit Metric Point limits.
Due to pre-allocation of MetricPoints in current implementation, there won't be any memory savings due to this. But we'll be able to accomodate more MetricPoints, by reclaiming unused points. This would mean the MetricPoint limit is the "limit of active points", rather than "limit of points seen since the beginning of process".

For cumulative aggregation:
Its possible to "forget" an un-used Metricpoint. However, if the forgotten point is reported again, we'll not be able to calculate cumulative since the process start. This would result in a reset (i.e start time will be reset).

### EDIT by utpilla:
This issue has been updated to only track MetricPoint reclaim for **Delta aggregation temporality only**.

**Comment by cijothomas** [comment] 2021-11-17 18:02
This issue is slightly related to https://github.com/open-telemetry/opentelemetry-dotnet/issues/2524, but more complex.
A few attempts were done to achieve this, see PRs: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2466
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2600 https://github.com/open-telemetry/opentelemetry-dotnet/pull/2598

Some observations:
1. To account for the possibility of a MetricPoint being reclaimed by someone else, the hot path has to do some synchronization mechanism. This has significantly affected throughput, in all the above PRs.
2. At the root, the issue is "atomically lookup which MetricPoint should be used for given tags, and do the update, without affecting performance". 
3. As proved by the PR attempts above, plain locks/ or even `ReadWriteLockSlim` cannot be used as is, without sacrificing performance.

This requires more investigation and time to address. For 1.2 release, https://github.com/open-telemetry/opentelemetry-dotnet/issues/2524 and https://github.com/open-telemetry/opentelemetry-dotnet/issues/2358 will be focused, and this issue will be re-investigated post 1.2

**Comment by reyang** [comment] 2021-11-17 20:15
Throwing couple ideas here:
1. the synchronization (lock) approach - break down the lock granularity - e.g. instead of having a single R/W lock for each point, having a per CPU core/group lock then decide if there is a need to escalate to a bigger lock.
2. non synchronization approach (even better) - leverage the page faults or segment access from memory manager to prevent stale writes (and the stale writes should result in a recoverable error + retry).

**Comment by tgrieger-sf** [comment] 2023-01-09 19:53
We are currently hitting an issue where we happen to have a metric with an ever increasing amount of unique tags which causes us to hit the max metric points per stream very quickly (even after increasing the max to 1,000,000). Is there any planned work around this or anything we can do to mitigate the issue until something permanent is in place?

**Comment by reyang** [comment] 2023-01-09 23:05
> We are currently hitting an issue where we happen to have a metric with an ever increasing amount of unique tags which causes us to hit the max metric points per stream very quickly (even after increasing the max to 1,000,000). Is there any planned work around this or anything we can do to mitigate the issue until something permanent is in place?

@tgrieger-sf could you share more about the scenario? (e.g. why do you need to put "an ever-increasing amount of unique tags" as metrics dimensions)

**Comment by reyang** [comment] 2023-01-10 00:09
@tgrieger-sf if these tables are created/dropped quickly, how do you use them as metrics dimension? (e.g. is the goal to get the unique count of tables?)

**Comment by reyang** [comment] 2023-01-10 01:03
@tgrieger-sf I wonder if "which parts of the application" have a limited/finite number of parts that can be derived from the ever-increasing names, if yes, could this be used as the actual dimension?

**Comment by tgrieger-sf** [comment] 2023-01-10 01:05
@reyang You're not wrong but the problem is that's not defined (it's being worked on but isn't a priority and won't be ready anytime soon).

**Comment by reyang** [comment] 2023-01-10 01:08
@tgrieger-sf based on the discussion, I feel that the "right" approach seems to be using [exemplars](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exemplar) to sample the table names, and avoid using the table names as a dimension.

**Comment by tgrieger-sf** [comment] 2023-01-10 01:16
@reyang I appreciate the conversation and I'll look into exemplars. Thanks!

**Comment by idoublefirstt** [comment] 2023-03-17 20:49
@reyang Any update on this? I'm an internal customer. We are trying to migrate to OpenTelemetry to emit SLI/SLO data which contains ArmId as part of metrics dimensions. Resources get created and deleted daily. It would be great to able to reclaim metrics points on deleted armIds to save some memory consumption. Our service is a quite large. With current design, it seems like we'd need to restart our monitoring service once a week to cleanup memory usage.

**Comment by reyang** [comment] 2023-03-18 00:59
@idoublefirstt this is a top item we plan to address before the next release https://github.com/open-telemetry/opentelemetry-dotnet/milestone/36. The actual time might vary depending on the prioritization and bandwidth.

**Comment by yoziv** [comment] 2023-03-18 11:36
I would like to also strengthen the case for that , in another internal group we have a big security related service which needs this ability greatly as we also need to support some kind of guide for our purpose and this feature is greatly needed

**Comment by cijothomas** [comment] 2023-03-20 16:57
Please follow this issue to be updated about this. Though its treated as high-priority, its not really in the 1.5 or 1.6 milestone. Its still high priority (no doubt!), but it is unlikely to land in 1.5 milestone. I'll propose to make this part of 1.6 milestone (which released later this year)

**Comment by utpilla** [comment] 2023-10-17 03:57
@tgrieger-sf @idoublefirstt @yoziv and to anyone else who has expressed interest in this feature, please try out the `1.7.0-alpha.1` [version](https://www.nuget.org/packages/OpenTelemetry/1.7.0-alpha.1) of OpenTelemetry SDK which offers this feature. I'd really appreciate any feedback.

**Comment by utpilla** [comment] 2023-12-09 00:37
> @tgrieger-sf @idoublefirstt @yoziv and to anyone else who has expressed interest in this feature, please try out the `1.7.0-alpha.1` [version](https://www.nuget.org/packages/OpenTelemetry/1.7.0-alpha.1) of OpenTelemetry SDK which offers this feature. I'd really appreciate any feedback.
> 
> You could check PR #4486 to know more about this feature.

There is an update in the Metrics SDK behavior. Instead of making this the default behavior of the SDK, we have offered it as an experimental opt-in only feature. You can opt-in to enable this behavior by setting `OTEL_DOTNET_EXPERIMENTAL_METRICS_RECLAIM_UNUSED_METRIC_POINTS` to `true` either using an environment variable or through IConfiguration. Check #5052 for more details.

**Comment by CodeBlanch** [comment] 2024-03-13 20:10
I'm going to close this because we have the feature work done. I opened #5443 for future work to make it stable.

**Closed by CodeBlanch** 2024-03-13 20:10 UTC
Labels: enhancement, priority:p1, metrics
