### ISSUE TITLE
OpenTelemetry.Exporter.Prometheus middleware - multitargeting net461 and netstandard2.0

### ISSUE THREAD

**Issue by marcusjsford** [open-telemetry/opentelemetry-dotnet#2401] opened 2021-09-22 10:31 UTC
# Question

`OpenTelemetry.Exporter.Prometheus`   `core-1.2.0-alpha3`

net461 is netstandard2.0 compatible so why does the OpenTelemetry.Exporter.Prometheus project need to target both? 

The OpenTelemetry.Exporter.Prometheus project targets netstandard2.0 and net461. And the `UsePrometheus` extension method has compiler preprocessor directives limiting the middleware functionality to only 
netstandard2.0. 

Because the project targets both net461 and netstandard2.0 when the package is referenced by a netframework application the net461 package is resolved making the `UsePrometheus` extension method unavailable to netframework applications even if they are netstandard2.0 compliant, resulting in a TypeLoadException.

`System.TypeLoadException: 'Could not load type 'OpenTelemetry.Exporter.Prometheus.PrometheusRouteBuilderExtensions' from assembly 'OpenTelemetry.Exporter.Prometheus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c'.`

[PrometheusRouteBuilderExtensions.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/core-1.2.0-alpha3/src/OpenTelemetry.Exporter.Prometheus/PrometheusRouteBuilderExtensions.cs#L17)
[PrometheusExporterMiddleware.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/core-1.2.0-alpha3/src/OpenTelemetry.Exporter.Prometheus/PrometheusExporterMiddleware.cs#L20)

Ideally when the OpenTelemetry.Exporter.Prometheus package is referenced from a netframework project that is netstandard2.0 compliant the `UsePrometheus` middleware would be available.

**Comment by cijothomas** [comment] 2021-09-22 16:36
The middleware option is not tested and quite likely not working - tracking it here: https://github.com/open-telemetry/opentelemetry-dotnet/issues/2400

> net461 is netstandard2.0 compatible so why does the OpenTelemetry.Exporter.Prometheus project need to target both?

It is the recommendation from .NET to include net461 target. https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

**Comment by cijothomas** [comment] 2021-09-23 19:02
Closing this as duplicate of #2400

**Closed by cijothomas** 2021-09-23 19:02 UTC
Labels: question
