### ISSUE TITLE
OpenTelemetry.dll-OpenTelemetry.BatchExportProcessor holding 50% of cpu even if the main process is inactive.

### ISSUE THREAD

**Issue by citrix-pradeep** [open-telemetry/opentelemetry-dotnet#3673] opened 2022-09-19 13:12 UTC
Using open telemetry for one of our w3wp process to get the app insights metrices but opentelemetry keeps consuming the cpu even if there is no activite reqest for w3wp.
Attaching the screenshot of windows performance recorder.
Note: it is **.NET framework version of the opentelemetry** and this issue is kind of intermittent.
![image](https://user-images.githubusercontent.com/8372198/191025091-2e1bd2b6-eaf7-4670-a6ff-cbf2ba3c3f5a.png)

**Comment by reyang** [comment] 2022-09-21 17:01
@rajkumar-rangaraj FYI

@citrix-pradeep any repro / dump / profile that you can provide?

**Comment by CodeBlanch** [comment] 2022-09-23 19:09
The `BatchExportProcessor<T>` class by default will wake up its thread every 5000ms to see if there is anything to export. So if your process is totally idle, you will see that happening regardless of request activity. Does that sound like it matches what you are observing?

We might be able to make it go totally quiet if there is nothing at all to export. I'll look into it a bit.

**Comment by reyang** [comment] 2022-09-24 18:51
Is this callstack here showing that enumerator is taking the time? @CodeBlanch

![image](https://user-images.githubusercontent.com/17327289/192114099-437fc8b0-ed21-4bc3-b05d-a9df283b31d0.png)

**Comment by CodeBlanch** [comment] 2022-09-26 17:33
I want to say yes, but I will say: unclear 😄 It would be helpful if @citrix-pradeep could provide what is below that as well.

What I do see...

* [BatchExportProcessor<T>](https://github.com/open-telemetry/opentelemetry-dotnet/blob/ed0450ef0ef5178cb29cb8908c3ff120a053caad/src/OpenTelemetry/BatchExportProcessor.cs#L281) won't call `Export` if there isn't any data. Makes me question that the process really is idle. Could be some health/status check being captured/exported constantly keeping it busy.

* There is a [sync-over-async](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#warning-sync-over-async) being performed in [AzureMonitorTraceExporter](https://github.com/Azure/azure-sdk-for-net/blob/f4b6edc0de76a5fda06644c2ac495941d5b070a0/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorTraceExporter.cs#L55) which is an anti-pattern, but it isn't under the enumerator so I think the stack would be different. It does smell though because IIRC that can lead to starvation, deadlocks, etc.

* `AzureMonitorTraceExporter` seems to be able to re-transmit stored data in the event of failure, but doesn't use `Batch<T>` to do it.

I did spin up a net48 app and try to reproduce this, but everything seems to be working fine. Need more ~food~ data!

**Comment by citrix-pradeep** [comment] 2022-09-29 14:04
@CodeBlanch @reyang let me collect few dumps with the same issue and will share with you soon.

**Comment by citrix-pradeep** [comment] 2023-02-07 04:27
@CodeBlanch @reyang debug diag or windbg dump will work for this or you need any specific dump.

**Comment by citrix-pradeep** [comment] 2023-02-07 04:29
Note: the issue being obserbed again after so long.

**Comment by reyang** [comment] 2023-02-07 06:35
@Yun-Ting FYI

**Comment by reyang** [comment] 2023-02-07 06:50
> @CodeBlanch @reyang debug diag or windbg dump will work for this or you need any specific dump.

A full dump would be helpful to show the internal state of the Batch<T> (which is likely to explain why the enumerator seems stuck) https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump#options-1

**Comment by citrix-pradeep** [comment] 2023-02-07 15:13
@CodeBlanch @reyang  Please find the full dotnet-dump here- 
https://drive.google.com/drive/folders/1Vmm_xGvy82MKKy-Vd2EcRVnJiYSfe5wB?usp=sharing

**Comment by citrix-pradeep** [comment] 2023-02-10 05:38
@CodeBlanch @reyang  by any chance did you got a chace to check above dumps?

**Comment by reyang** [comment] 2023-02-10 17:19
@citrix-pradeep I had a brief look, although I don't have the full theory yet but here is my guess:

The exporter thread is stuck at a live loop https://github.com/open-telemetry/opentelemetry-dotnet/blob/94f67d8a8cd7b60ed309d3bb632b373f3415dc38/src/OpenTelemetry/Internal/CircularBuffer.cs#L168-L172, the intention was to wait for other threads to write the actual value to the circular buffer. Somehow another thread which is supposed to fill in the value either didn't finish the work due to starvation, or because the thread got killed accidentally which broke the integrity. I quickly scanned the other threads and there doesn't seem to be one trying to write https://github.com/open-telemetry/opentelemetry-dotnet/blob/94f67d8a8cd7b60ed309d3bb632b373f3415dc38/src/OpenTelemetry/Internal/CircularBuffer.cs#L136-L146, or maybe there is a synchronization bug in the OpenTelemetry .NET SDK.

![image](https://user-images.githubusercontent.com/17327289/218153718-48c6a1b2-0526-477f-aad2-67194b36c568.png)

My question for you @citrix-pradeep, do you have any clue if the app/service can have threads randomly killed at any point of execution? If there is a way you could help to record all the thread creation/abortion during the lifecycle of the process, it will help to nail down the problem.

**Comment by reyang** [comment] 2023-02-10 20:58
![image](https://user-images.githubusercontent.com/17327289/218196230-a35a5c1a-ee78-4325-af69-06050c5af96a.png)

**Comment by reyang** [comment] 2023-02-10 22:47
@CodeBlanch and I took some further analysis and we believe this was a known issue on x86 (32bit) that has been addressed in #3349. @citrix-pradeep you should be able to get rid of the problem by upgrading to a newer version which includes the fix.

**Closed by reyang** 2023-02-10 22:47 UTC

**Comment by citrix-pradeep** [comment] 2023-02-11 04:04
Thanks @reyang @CodeBlanch  ...
Any idea which version have the fix for this.

**Comment by reyang** [comment] 2023-02-11 05:21
> Thanks @reyang @CodeBlanch ... Any idea which version have the fix for this.

You can use the latest stable version.
