### ISSUE TITLE
Moving docs to opentelemetry.io

### ISSUE THREAD

**Issue by mic-max** [open-telemetry/opentelemetry-dotnet#2876] opened 2022-02-08 23:51 UTC
To track the efforts of moving our documentation from current `/docs/` directory to [here](https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/docs/instrumentation/net)

- [ ] Duplicate documents to opentelemetry.io repository
- [ ] Delete files here
- [ ] Make source code snippets be included directly from their files (not copy pasted into the docs)
- [ ] Make expected output snippers included from files that are updated when the tests change

Optional
- [ ] Create a docs repository for demo programs like [java did](https://github.com/open-telemetry/opentelemetry-java-docs)

**Comment by mic-max** [comment] 2022-02-10 22:54
> > * Make source code snippets be included directly from their files (not copy pasted into the docs)
> 
> Btw, I've started using the basic shortcode [code_block_from](https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/shortcodes/code_block_from.md) for the Python docs -- e.g., at:
> 
> * https://github.com/open-telemetry/opentelemetry.io/blame/main/content/en/docs/instrumentation/python/getting-started.md#L33
> 
> If you have a shortcode of your own, or have specific needs and would like me to work on a shortcode for you, let me know.

That's awesome! I'll make use of it!

**Comment by cijothomas** [comment] 2024-09-18 03:05
Close as duplicate of https://github.com/open-telemetry/opentelemetry-dotnet/issues/5365

**Closed by cijothomas** 2024-09-18 03:05 UTC
