### ISSUE TITLE
When does Opentlemetry.NET SDK support  EntityframeworkCore tracing Collector?

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#229] opened 2019-09-25 07:31 UTC

**Comment by lmolkova** [comment] 2019-09-25 17:40
For the next several months we are focusing on shipping production-ready stable version of core components. We'll be looking into extending auto-collectors after that.

**Comment by cijothomas** [comment] 2019-09-30 23:54
Duplicate of: https://github.com/open-telemetry/opentelemetry-dotnet/issues/79

**Comment by lmolkova** [comment] 2019-10-12 17:55
Closing as duplicate

**Closed by lmolkova** 2019-10-12 17:55 UTC
Labels: enhancement, question
