### ISSUE TITLE
Asynchronous processors/exporters

### ISSUE THREAD

**Issue by ghelyar** [open-telemetry/opentelemetry-dotnet#1395] opened 2020-10-26 14:31 UTC
# Feature Request

**Is your feature request related to a problem?**

Exporting telemetry is likely to be an I/O based operation, such as writing it to a file or a socket.

The built-in types for exporting logs and traces, such as `BaseProcessor`, `BatchExportProcessor` and `BaseExporter` are synchronous. This means that any asynchronous calls need to be synchronously waited, using something like `.GetAwaiter().GetResult()`, as seen in the `ZipkinExporter`.

`MetricExporter` is already asynchronous.

**Describe the solution you'd like:**

It would be nice if these methods were asynchronous e.g. `Task<ExportResult> BaseExporter.ExportAsync(in Batch<T> batch, CancellationToken cancellationToken)`.

**Comment by CodeBlanch** [comment] 2020-10-28 00:14
Hey @ghelyar! This is kind of tricky to answer. They used to all be asynchronous. But the spec is very specific about how the exporters work. From https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#exportbatch:

> Export() will never be called concurrently for the same exporter instance. Export() can be called again only after the current call returns.

At the moment writing into the batch is done [highly] concurrently using a special circular buffer. Export happens on a dedicated thread once the buffer has enough data or on an interval.

So this is all very much by design. Zipkin is doing `.GetAwaiter().GetResult()` because HttpClient doesn't have a synchronous API. Not sure how to solve that, at the moment. Any ideas?

/cc @reyang

**Comment by reyang** [comment] 2020-10-28 00:32
@ghelyar would you help us to understand what are the outcome you would expect? For example, do you expect the exporting thread to be reused (e.g. share a pool of worker threads), or the export API to be async for easier integration with other async I/O APIs?

**Comment by ghelyar** [comment] 2020-10-28 08:41
It was just to make it easier to write exporters. As exporters are very likely to use I/O, I expected it to have an `ExportAsync`. It's a bit nicer implementing `ExportAsync` and returning with a `Task.FromResult` than implementing `Export` and using `GetAwaiter().GetResult()`.

`BatchExportProcessor` using a background thread does make `ExportAsync` a bit less useful, although defining the shape of all exporters to be synchronous because one processor (albeit probably the most frequently used processor) has a background thread seems like the implementation is leaking into the abstraction a bit.

In terms of implementation, maybe add a `virtual ValueTask<ExportResult> ExportAsync` to `BaseExporter`, and also make `Export` virtual, with the default implementation of `Export` to call `ExportAsync(batch).GetAwaiter().GetResult()`. Exporter implementations can then choose whether to implement `Export` or `ExportAsync`.

If the processors are synchronous and can't fire and forget the exports, that synchronous blocking has to happen somewhere I suppose.

**Comment by reyang** [comment] 2020-10-29 01:24
> In terms of implementation, maybe add a `virtual ValueTask<ExportResult> ExportAsync` to `BaseExporter`, and also make `Export` virtual, with the default implementation of `Export` to call `ExportAsync(batch).GetAwaiter().GetResult()`. Exporter implementations can then choose whether to implement `Export` or `ExportAsync`. However, any processors that do exporting would still need to call `Export`, which possibly makes writing an exporter easier at the expense of making writing a processor more error prone. The only ways I can think of to get around that is to completely remove `Export` and have processors do the `GetAwaiter().GetResult()`, or to introduce another abstract class below `BaseExporter` that maps from `Export` to an abstract `ExportAsync`.

Like the idea! I think this is doable and has a potential to simply the job of writing exporters using async I/O.

**Comment by markrendle** [comment] 2022-01-26 17:30
I've been playing with a trace Exporter that writes to Azure Table Storage and came looking for this issue.

For each Trace, the exporter writes to multiple tables (two or three depending on content), and also writes in batches. Maximum batch size for Azure Tables is 100, maximum batch size looks like 512, so there may be up to eighteen separate calls to table storage for a given batch.

The [Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables/) package has non-async methods (although I think those are calling `GetAwaiter().GetResult()` on the underlying `HttpClient` anyway) but using those methods would mean those writes had to run serially. Using the `Async` methods I can gather a bunch of `Task`s together and `await Task.WhenAll` so the writes can happen in parallel.

Currently I'm just doing `Task.WhenAll(tasks).ConfigureAwait(false).GetAwaiter().GetResult()` to block, but as OP said, having an `ExportAsync` overload would feel cleaner.

**Comment by ghelyar** [comment] 2022-01-26 18:27
For what it's worth, reactive extensions is very similar and lets you do this as an asynchronous operation can be mapped 1:1 to an observable. You can just use something like `Buffer` and `SelectMany`.

These don't block while it writes so multiple batches may be writing at the same time, but this might go against the otel spec.

I think if you really want to do this then the answer might be to just write your own processor rather than using the built in batch processor, and then call your exporter asynchronously.

**Comment by markrendle** [comment] 2022-02-02 15:27
The issue with using an `IObservable` (or a Channel or whatever) and offloading the write to run asynchronously is that the `Export` method returns a result saying whether the export was successful or not. If you offload to a background process of any kind you can't return an honest result: you don't know whether the data was actually written to the external store or not.

**Comment by ghelyar** [comment] 2022-02-02 16:49
Yes, you are effectively telling OpenTelemetry that you have successfully published to an in-memory sink, and it's up to something else to persist that. It's really just a work around for a limitation of OpenTelemetry.

You can also write your own processor that calls your exporter asynchronously, but unless you're willing to overlap the asynchronous exports it doesn't really gain you very much.

If you want it to finish writing one set of events before it starts writing the next, which I think is what the spec says it must do, the current implementation does that, it just doesn't smell very nice that the processor expects all exporters to be synchronous when really most exporters will want to do some asynchronous I/O.

**Comment by purkhusid** [comment] 2023-03-09 10:22
Just to chime in here. I had an hard to debug problem with one of my AWS Lambda functions that was very slow for some unknown reason.

The culprit proved to be the tracing exporter which was blocking threads which caused everything else to be slow. The reason the blocks were so slow is that I was sending traces directly to a vendor which caused latency in the export and that caused the thread blocks to last for longer.

The workaround for me was to use the AWS Lambda collector(https://github.com/open-telemetry/opentelemetry-lambda/tree/main/collector) so that I could export to `localhost` and then the traces are exported to the vendor by the extension. This removed the network latency during the function execution and thus removed most of the issues caused by the blocking trace exporter.

**Comment by dhhoang** [comment] 2023-05-22 11:33
> I don't see what `virtual ValueTask<ExportResult> ExportAsync` really accomplishes. That just pushes the problem up to the caller (SDK) to do `GetAwaiter().GetResult()`. This is the [Sync over async](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#warning-sync-over-async) anti-pattern. The issue is we already have a dedicated thread for exporting. So starting a Task to do the work while we block that thread is just tying up 2 threads. Unless we force the task to run on the same thread. Might be a way to do that, I don't know of it off the top of my head but maybe runtime team can provide some insight.

Another reason for an async interface is supporting cancellation scenarios such as timeout, graceful shutdown etc.  From the spec:
> Export() MUST NOT block indefinitely, there MUST be a reasonable upper limit after which the call must time out with an error result (Failure).

As far as I'm aware the `Process*()` methods in the base exporters simply ignore the `timeout` parameter, for example: https://github.com/open-telemetry/opentelemetry-dotnet/blob/1510b76634f4fdfbf79cd73e4b71aaf474e40a46/src/OpenTelemetry/Metrics/BaseExportingMetricReader.cs#L87

Also, I don't think having `ExportAsync` means that the SDK is required to call `GetAwaiter().GetResult()`. This is only needed because currently the exporter uses a dedicated thread to pull the circular buffer and send. We can replace the `Thread` with a `Task` that runs the same loop (which calls `await ExportAsync()`) and let the threadpool takes care of executing it .

**Comment by martinjt** [comment] 2024-02-22 13:49
There's been a lot of ideas in this thread that are great, however I've not seen anyone take the job of doing it. It doesn't look like the core team is planning on implementing this so I'm going to close this as not planned.

If this is something that you care deeply about and want to do the work, feel free to reach out and we'll be happy to help guide you on the process of contributing the work!

**Closed by martinjt** 2024-02-22 13:49 UTC
Labels: enhancement, area:sdk, area:exporter

**Comment by carlcamilleri** [comment] 2025-04-07 14:56
Apologies for re-opening an old issue, however as it has already been pointed out that this is the [Sync over async](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#warning-sync-over-async) anti-pattern, has anyone noticed performance issues with thread pool starvation due to this?

Currently facing a problem where both application behaviour and samplers data are pointing towards thread pool starvation, with samplers data showing that ~50% of the CPU time is blocked by GRPC calls. The only GRPC calls in the application are done by the OTEL exporter

**Comment by kamilzzz** [comment] 2026-02-19 07:16
I don't quite get the explanation.

Why would quote from specification:

> Export() will never be called concurrently for the same exporter instance. Export() can be called again only after the current call returns.

imply exporters need to be synchronous?
