### ISSUE TITLE
ILogger logs not reflecting correct application name

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [open-telemetry/opentelemetry-dotnet#5560] opened 2024-04-22 21:27 UTC
# Bug Report

Azure.Monitor.OpenTelemetry.AspNetCore 1.1.0
OpenTelemetry.Exporter.Console 1.8.1
OpenTelemetry.Instrumentation.Process1.0.0-alpha.6
OpenTelemetry.Instrumentation.Runtime 1.8.0

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

<TargetFramework>net8.0</TargetFramework>

## Symptom

**What is the expected behavior?**

That just like the requests and metrics, the log would have the correct App Service Name

**What is the actual behavior?**

The app name `unknown_service:dotnet`

## Reproduce

Create a new web api, default template... add the packages above and in the program.cs do

```
public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        var resourceAttributes = new Dictionary<string, object> { { "service.name", "Flex Backend Mocker" } };

        builder.Services.AddOpenTelemetry()
                        .ConfigureResource(cfg => cfg.AddAttributes(resourceAttributes))
                        .WithMetrics(builder => builder.AddAspNetCoreInstrumentation().AddRuntimeInstrumentation().AddProcessInstrumentation().AddConsoleExporter())
                        .WithTracing(builder => builder.AddAspNetCoreInstrumentation().AddConsoleExporter())
                        .UseAzureMonitor(cfg =>
                        {
                            cfg.ConnectionString = "yourConnectionStringToAzureAppInsightsHere";
                        });

        // Add services to the container.
        builder.Services.AddMemoryCache();
        builder.Services.AddControllers();
        builder.Services.AddSingleton<Random>();

        var app = builder.Build();

        app.MapControllers();

        app.Run();
    }
}
```

Then run. Using a tool like Fiddler, you can capture the requests going out and you will see that only the logs like "application started etc" have the app name set to `unknown_service:dotnet`

## Additional Context

N/A

**Comment by cijothomas** [comment] 2024-04-22 21:36
Can you follow https://github.com/open-telemetry/opentelemetry-dotnet/issues/5551#issuecomment-2064591507 ?

**Comment by rajkumar-rangaraj** [comment] 2024-04-22 22:43
`Azure.Monitor.OpenTelemetry.AspNetCore` had an issue where logs were using a different resource attributes. This was fixed in the 1.2.0-beta.3 version. Could you please try the new package and check if the issue is resolved? I recommend testing the behavior without the `UseAzureMonitor` API. If you have an issue related to that specific package, please post your question at https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore.

**Comment by Leonardo-Ferreira** [comment] 2024-04-22 23:10
well, yes it solved this issue, but created another: now there are extra properties... like, my logged message is "Will Delay for 123ms" and now I have a extra property like `{"0":"472"}`

**Comment by cijothomas** [comment] 2024-04-22 23:26
> well, yes it solved this issue, but created another: now there are extra properties... like, my logged message is "Will Delay for 123ms" and now I have a extra property like `{"0":"472"}`
> 
> is there a way to turn off this "auto-enrichment"?

Are you seeing that enrichment in AzureMonitor only? or when using ConsoleExporters (or OTLP) ?

**Comment by Leonardo-Ferreira** [comment] 2024-04-23 20:38
Only in azure monitor, this enrichment is not visible on the console

**Comment by cijothomas** [comment] 2024-04-24 00:30
> Only in azure monitor, this enrichment is not visible on the console

mm. Strange! Not sure what's going on. I'd suggest to report it at azure-monitor repo.

**Closed** 2024-04-24 00:30 UTC
Labels: bug
