### ISSUE TITLE
OpenTelemetry.Instrumentation.AspNetCore does not produce metrics or traces when using ASP.NET Core 2.1

### ISSUE THREAD

**Issue by mathew-tolj** [open-telemetry/opentelemetry-dotnet#5019] opened 2023-11-02 20:05 UTC
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Exporter.Console 1.6.0
* OpenTelemetry.Extensions.Hosting 1.6.0
* OpenTelemetry.Instrumentation.AspNetCore 1.6.0-beta.2

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net472

## Symptom

When using OpenTelemetry.Instrumentation.AspNetCore with ASP.NET Core 2.1 no metrics or traces are exported for incoming requests.

**What is the expected behavior?**

Upon receiving an incoming HTTP request the service should export a corresponding span and the http.server.request.duration instrument.

**What is the actual behavior?**

No spans or instruments are exported.

The following messages appear in the self-diagnostics log:

```text
2023-11-02T01:31:20.3172867Z:Payload is NULL, span will not be recorded. HandlerName: '{0}', EventName: '{1}', OperationName: '{2}'.{HttpInListener}{OnStartActivity}{Microsoft.AspNetCore.Hosting.HttpRequestIn}
2023-11-02T01:31:21.2379449Z:Payload is NULL, span will not be recorded. HandlerName: '{0}', EventName: '{1}', OperationName: '{2}'.{HttpInListener}{OnStopActivity}{Microsoft.AspNetCore.Hosting.HttpRequestIn}
2023-11-02T01:31:21.2389450Z:Payload is NULL, span will not be recorded. HandlerName: '{0}', EventName: '{1}', OperationName: '{2}'.{HttpInMetricsListener}{OnStopActivity}{http.server.request.duration}
```

## Reproduce

```csharp
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.7" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.6.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.6.0-beta.2" />
  </ItemGroup>

</Project>
```

```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using OpenTelemetry.Metrics;
using OpenTelemetry.Trace;

namespace OpenTelemetryTesting;

internal class Program
{
    private const string ResponseBody = "Hello World";

    private static IWebHostBuilder CreateWebHostBuilder(string[] args)
        => WebHost
            .CreateDefaultBuilder(args)
            .ConfigureServices(
                services =>
                {
                    services
                        .AddOpenTelemetry()
                        .WithMetrics(
                            builder =>
                            {
                                builder.AddAspNetCoreInstrumentation();
                                builder.AddConsoleExporter();
                            })
                        .WithTracing(
                            builder =>
                            {
                                builder.AddAspNetCoreInstrumentation();
                                builder.AddConsoleExporter();
                            });
                })
            .Configure(
                app =>
                {
                    app.Map(
                        "/Hello",
                        subApp =>
                        {
                            subApp.Run(
                                context =>
                                {
                                    context.Response.ContentType = "text/plain";
                                    context.Response.ContentLength = ResponseBody.Length;
                                    return context.Response.WriteAsync(ResponseBody);
                                });
                        });
                });

    private static Task Main(string[] args) => CreateWebHostBuilder(args).Build().RunAsync();
}
```

## Additional Context

After doing my own investigation I suspect that the cause of this issue is that versions of ASP.NET Core lower than 3.0 wrap the `HttpContext` in an anonymous type before passing it as an argument when calling `DiagnosticListener.StartActivity` ([link](https://github.com/dotnet/aspnetcore/blob/76f3e3bd1c8a667248cb64f8563a8b64ed4f48d3/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L267)) and `DiagnosticListener.StopActivity` ([link](https://github.com/dotnet/aspnetcore/blob/76f3e3bd1c8a667248cb64f8563a8b64ed4f48d3/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L280C17-L280C17)). I believe this then causes `HttpInListener` ([link](https://github.com/open-telemetry/opentelemetry-dotnet/blob/5cc1f39cbd16b5a741985b2cfe1ac3da496a48f2/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L285C1-L290)) and `HttpInMetricsListener` ([link](https://github.com/open-telemetry/opentelemetry-dotnet/blob/5cc1f39cbd16b5a741985b2cfe1ac3da496a48f2/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs#L56C1-L61)) to stop processing the messages as the `payload` cannot be cast to `HttpContext`.

**Comment by cijothomas** [comment] 2023-11-02 20:25
Such special handling for Asp.Net Core 2.1 is not done, and is unlikely to be done as well... Your best option would be upgrade to newer versions of the framework :(

**Comment by cijothomas** [comment] 2023-11-02 20:28
https://github.com/open-telemetry/opentelemetry-dotnet/issues/4126 also discussed here.

**Comment by cijothomas** [comment] 2024-02-14 02:58
Can be closed as duplicate of 4126

**Closed by cijothomas** 2024-02-14 02:58 UTC
Labels: bug
