### ISSUE TITLE
[Logs] ObjectDisposedException in ASP.NET Core Instrumentation on Windows

### ISSUE THREAD

**Issue by tanaka-takayoshi** [open-telemetry/opentelemetry-dotnet#2906] opened 2022-02-16 15:19 UTC
Hi, I found the issue happens with ASP.NET Core Instrumentation **only on Windows.** The same code is working fine on Mac but it crashed with the ObjectDisposedException on Windows. 
It looks related #2905.

Here is the project file.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta2" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.2.0-rc2" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.2.0-rc2" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.0.0-rc9" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9" />
		<PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
	</ItemGroup>
</Project>
```

Here is how to configure the OTLP exporter in ASP.NET Core startup code.

```
builder.Logging.AddOpenTelemetry(builder =>
{
    builder.IncludeFormattedMessage = true;
    builder.IncludeScopes = true;
    builder.ParseStateValues = true;
    builder.SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("Hello-Otel").AddAttributes(tags))
        .AddOtlpExporter(options =>
        {
            options.Endpoint = new Uri("http://localhost:4317/");
        });
});
```

Here is how to output the log.

```
app.MapGet("/weatherforecast", (ILogger<Program> logger) =>
{
    logger.LogInformation("Log!!");
    return "example";
});
```

And exception details.

```
System.ObjectDisposedException
  HResult=0x80131622
  Message=IFeatureCollection has been disposed.
ObjectDisposed_ObjectName_Name
  Source=Microsoft.Extensions.Features
  StackTrace:
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Protocol()
   at Microsoft.AspNetCore.Hosting.HostingRequestStartingLog.get_Item(Int32 index)
   at Microsoft.AspNetCore.Hosting.HostingRequestStartingLog.<GetEnumerator>d__11.MoveNext()
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.LogRecordExtensions.ToOtlpLog(LogRecord logRecord)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.LogRecordExtensions.AddBatch(ExportLogsServiceRequest request, Resource processResource, Batch`1& logRecordBatch)
   at OpenTelemetry.Exporter.OtlpLogExporter.Export(Batch`1& logRecordBatch)
   at OpenTelemetry.BatchExportProcessor`1.ExporterProc()
   at System.Threading.Thread.StartCallback()
```

To avoid this issue, we can add `options.ExportProcessorType = OpenTelemetry.ExportProcessorType.Simple;` as @justkao mentioned [here](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1933#issue-838876329) in additonal context.

_Originally posted by @tanaka-takayoshi in https://github.com/open-telemetry/opentelemetry-dotnet/issues/1933#issuecomment-1037805669_

**Comment by cijothomas** [comment] 2022-02-17 03:18
Closing this as I can confirm that this one is duplicate of https://github.com/open-telemetry/opentelemetry-dotnet/issues/2905
Will keep 2905 for further discussions.
Thanks for reporting!

**Closed by cijothomas** 2022-02-17 03:18 UTC
