### ISSUE TITLE
Retry functionality not for traces and metrics

### ISSUE THREAD

**Issue by venkatramanchandirasekaran** [open-telemetry/opentelemetry-dotnet#2699] opened 2021-11-29 15:17 UTC
# Question

**Describe your environment.**
ASP.NET core and using Open telemetry .NET framework to send traces.

Describe any aspect of your environment relevant to the question.
LOCAL DEBUGGING and TESTING

**What are you trying to achieve?**
Based on OTEL spec, there should be retry functionality built it for traces and metrics if there are errors or end point not reachable. I don't see that built in to the  Open telemetry .NET framework.  This issue  is based on GIT hub documentation on how OTEL spec is defined
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-concurrent-requests

What did you expect to see?
I expect the trace and metrics calls to be kept in a queue and some retry functionality to send the data to the collector end point, but there is no retry functionality built in.

## Additional Context
Here is the exception i see but it doesnot retry. Also review the attached document for more details.
OpenTelemetry-Exporter-OpenTelemetryProtocol - EventId: [2], EventName: [FailedToReachCollector], Message: [Exporter failed send data to collector. Data will not be sent. Exception: Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="")

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it
[OTEL-retry.docx](https://github.com/open-telemetry/opentelemetry-dotnet/files/7619092/OTEL-retry.docx)
.

**Comment by cijothomas** [comment] 2021-11-29 17:03
> I expect the trace and metrics calls to be kept in a queue and some retry functionality to send the data to the collector end point, but there is no retry functionality built in.  

Yes, the above is correct. There is no functionality to retry/manage items in memory/disk today, but it may come in the future.

**Comment by cijothomas** [comment] 2021-11-29 18:21
linking to correct section of the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#retry

**Comment by venkatramanchandirasekaran** [comment] 2021-11-29 18:47
Thanks a lot for the confirmation. Few additional questions

1) Is retry functionality already planned for upcoming release ? 
2) Are there any metrics around how many traces / metrics failed that can be configured to get some insights in to this ?
3) Are there plans to expose the logs when there are failures. Currently it writes to Debug.WriteLine and that is not easy to pull out for additional analysis

**Comment by alanwest** [comment] 2021-11-29 23:35
Related #1779.

> Are there plans to expose the logs when there are failures. Currently it writes to Debug.WriteLine and that is not easy to pull out for additional analysis

You can enable the self-diagnostics feature described here to enable logging https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#troubleshooting

**Comment by venkatramanchandirasekaran** [comment] 2021-12-06 15:34
Do you have any updates.

**Comment by venkatramanchandirasekaran** [comment] 2021-12-06 15:34
Can we output these messages to regular console instead of the file. We run on containers and cannot use these files when the POD is destroyed.

**Comment by alanwest** [comment] 2021-12-08 01:16
The self-diagnostics feature does not currently have a way to emit events to the console instead of a file. However, the feature is built using .NET's [`EventSource`](https://docs.microsoft.com/dotnet/api/system.diagnostics.tracing.eventsource) for logging, so instead of using the self-diagnostics feature you could write a simple [`EventListener`](https://docs.microsoft.com/dotnet/api/system.diagnostics.tracing.eventlistener.oneventwritten) that subscribes to the SDK's events and write them to the console.

Though, if you'd like to avoid writing your own EventListener, you could open a feature request for adding an option to the self-diagnostics to write to stdout instead of a file.

**Comment by venkatramanchandirasekaran** [comment] 2021-12-08 14:41
Thanks a lot. How do i open a feature request ?

**Comment by cijothomas** [comment] 2022-01-28 16:46
Closing as duplicate of https://github.com/open-telemetry/opentelemetry-dotnet/issues/2699

**Closed by cijothomas** 2022-01-28 16:46 UTC
Labels: question
