### ISSUE TITLE
Add a link to the CHANGELOG when publishing a package to NuGet

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet#4011] opened 2022-12-15 05:42 UTC
Add a link to the CHANGELOF when publishing a package to NuGet. Consider this package for reference: https://www.nuget.org/packages/Microsoft.OpenTelemetry.Exporter.AzureMonitor/1.0.0-beta.1#release-body-tab

This would help to understand the exact changes that went into any version of a package. Currently, it's tough to find the list of changes made for any patch/hotfix version of a package. For example: 1.3.1 has a patch on top of 1.3.0. However, we don't have any entry for 1.3.1 in the `main` branch CHANGELOG. This makes it tough to know what changes were made to 1.3.1. As of today, it requires the user to select the 1.3.1 branch instead of main and check the CHANGELOG. These changes could be made more easily available if we could just add a link to the CHANGELOG under Release Notes or README when we publish a package.

**Comment by TimothyMothra** [comment] 2024-09-26 21:49
duplicate of #4895

**Closed by TimothyMothra** 2024-09-26 21:49 UTC
Labels: enhancement
