### ISSUE TITLE
AspNet Net 6.0: FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0

### ISSUE THREAD

**Issue by ggallotti** [open-telemetry/opentelemetry-dotnet#4047] opened 2022-12-28 13:22 UTC
# Question
When using the latest version of the OpenTelemetry NuGet package (currently 1.4.0-rc.1) an AspNetCore Net6.0 fails to start because OTel has taken a dependency on System.Diagnostics.DiagnosticSource 7.0.0.

```
  <ItemGroup>
	  <PackageReference Include="OpenTelemetry.Api" Version="1.4.0-rc.1" NoWarn="NU5104" />
	  <PackageReference Include="OpenTelemetry" Version="1.4.0-rc.1" NoWarn="NU5104" />
	  <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-rc.1" NoWarn="NU5104" />
	  <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0-rc.1" NoWarn="NU5104" />
	  <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.4.0-rc.1" NoWarn="NU5104" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.10" NoWarn="NU5104" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.10" NoWarn="NU5104" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9.10" NoWarn="NU5104" />	  
  </ItemGroup>
```

When running an ASP.NET NET6.0 App, an exception ocurrs:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OpenTelemetry.Sdk' threw an exception.
  Source=OpenTelemetry
  StackTrace:
   at OpenTelemetry.Sdk.get_SuppressInstrumentation()
   at Microsoft.Extensions.DependencyInjection.ProviderBuilderServiceCollectionExtensions.AddOpenTelemetrySharedProviderBuilderServices(IServiceCollection services)
   at OpenTelemetry.Trace.TracerProviderBuilderBase..ctor()
   at OpenTelemetry.Trace.TracerProviderBuilderHosting..ctor(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetryTracing(IServiceCollection services, Action`1 configure)
   at App.OpenTelemetry.OpenTelemetry.OpenTelemetryProvider.InstrumentAspNetCoreApplication(IServiceCollection services) in D:\DEV\git\DotNetClasses\dotnet\src\dotnetcore\Providers\OpenTelemetry\OpenTelemetry\OpenTelemetryProvider.cs:line 17
   at App.Services.OpenTelemetry.OpenTelemetryService.Setup(IServiceCollection services) in D:\DEV\git\DotNetClasses\dotnet\src\dotnetcore\GxClasses\Services\OpenTelemetry\OpenTelemetryService.cs:line 48
   at App.Application.Startup.ConfigureServices(IServiceCollection services) in D:\DEV\git\DotNetClasses\dotnet\src\dotnetcore\GxNetCoreStartup\Startup.cs:line 140
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)

  This exception was originally thrown at this call stack:
    [External Code]
    GxClasses.Helpers.AssemblyLoader.LoadContext_Resolving(System.Runtime.Loader.AssemblyLoadContext, System.Reflection.AssemblyName) in CompatibilityExtensions.cs
    [External Code]

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

```

It seems that DiagnosticSource is not compatible with .NET6? 
Seems to be related to this Issue: https://github.com/Azure/azure-functions-host/issues/8938

**Comment by alanwest** [comment] 2022-12-28 18:59
@ggallotti Are you experiencing this with an azure function or is this just a regular asp.net core application?

**Comment by ggallotti** [comment] 2022-12-28 19:14
Just a regular Asp.Net (Net6.0) Application. Downgraded to 1.4.0-alpha.1 with no Issues.

**Comment by alanwest** [comment] 2022-12-28 19:47
> It seems that DiagnosticSource is not compatible with .NET6?

DiagnosticSource 7.0 is compatible with .NET 6.

Using our [example ASP.NET Core app](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/AspNetCore), I'm not able to reproduce what you're seeing. The app is a .NET 6 application.

Do you have a minimal repro you can provide?

**Comment by ggallotti** [comment] 2022-12-29 17:56
@alanwest, you are right. Just tested a minimal NET6 APP and it's working. 
Seems some dependency Issue in my installation.
Sorry for the trouble and thank for your response.

**Comment by PiotrSzydloRelativity** [comment] 2023-01-11 09:47
Same situation after adding OpenTelemetry 1.4.0-rc.2
'System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.''

**Comment by 98christianp** [comment] 2023-01-20 10:07
+1 getting this as well - I'm running on a function though! What was the problem @ggallotti ?

> Same situation after adding OpenTelemetry 1.4.0-rc.2 'System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.''

**Comment by PiotrSzydloRelativity** [comment] 2023-01-20 12:04
The stable version 1.3.2 worked for me

**Comment by 98christianp** [comment] 2023-01-20 12:11
> The stable version 1.3.2 worked for me

Yep, also went in and downgraded all packages that had Opentelemetry >= 1.4.0 as a dependency and got it working. According to the thread https://github.com/Azure/azure-functions-host/issues/8938 Otel stuff in 1.4 is a RC right now, so perhaps it makes sense to not use those versions by default.

**Comment by martinjt** [comment] 2023-01-21 15:07
Unfortunately azure functions that aren't using isolated mode will not work. This is because the function Runtime has a hard dependency on 6.0.0 of System.DiagnosticSource. it requires the Azure functions to fix, which I wouldn't expect to happen given they are trying to deprecate them.

I'm really looking for a reproduction of this. Obviously we can't ask people to post private projects, however, if you have a way to reproduce it that you're willing to share over a video call I'll happily make the time.

https://www.honeycomb.io/devrel/observability-office-hours

There is likely something funky in build processes or clients thar we need to get to the bottom of.

**Comment by cijothomas** [comment] 2023-02-08 17:18
@martinjt the repro is pretty straightforward in Functions. One minimal repro is already shared in the linked issue.
I also found another user posting one : https://github.com/cijothomas/FunctionsOpenTelemetry/issues/2

**Comment by cijothomas** [comment] 2023-02-14 16:48
https://github.com/Azure/azure-functions-host/issues/8938#issuecomment-1429283928  See the tracking issue in Functions repo. Unfortunately, this limitation will be there for the foreseeable future, and only workaround is isolated model.
I am closing the issue in this repo, as this is purely a limitation of Functions in-proc model.

If anyone sees the issue in other environment, please reopen. 
Thanks!

**Closed by cijothomas** 2023-02-14 16:48 UTC
Labels: question

**Comment by cataggar** [comment] 2023-05-11 21:38
Another workaround was provided in a [comment](https://github.com/Azure/azure-functions-host/issues/8938#issuecomment-1494697036) that works with in-process model.

``` xml
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Diagnostics.DiagnosticSource.dll" />
```

**Comment by cijothomas** [comment] 2023-06-20 18:05
> @cijothomas why can we not decide to create a net6 and net3.1 version that specifies the DiagnosticSource version? This is the best approach
> 
> is not a good solution if e.g
> 
> Say 6.0 DLL has function createactivity(string name, string somethingelse). 7.0 has createactivity(string somethingelse, string name) ?

OpenTelemetry need the *latest* version of DiagnosticSource in all .NET runtimes.
See https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/Directory.Packages.props#L28-L37

**Comment by rsr-maersk** [comment] 2023-07-07 08:04
@cijothomas Open Telemetry is not working with AZ FUncs even after 
`<FunctionsPreservedDependencies Include="System.Diagnostics.DiagnosticSource.dll" />`

We need a System.X for version 3.1.* and for version 6.0.*. This was the same problem other packages had with system. configuration 5 on AZ Func 3 )
