### ISSUE TITLE
BatchExportProcessor should expose metrics

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [open-telemetry/opentelemetry-dotnet#1734] opened 2021-01-28 01:04 UTC
# Feature Request

**Is your feature request related to a problem?**

Current it doesn't appear be possible to monitor buffer insert failures in the BatchExportProcessor. This can lead to situations where the buffer is full and traces are dropped without the application owner being aware. 

**Describe the solution you'd like:**

The exporters should provide a way to monitor their success/failure/latency

## Additional Context

We're currently using the zipkin exporter with the BatchExportProcessor

**Comment by reyang** [comment] 2021-01-28 03:41
There are two places where work needs to happen:
1. BatchExportProcessor has an internal field `droppedCount` to track the processor item drop (due to buffer full). This information should be exposed in a proper way to the application owner.
2. Exporter will potentially need to handle retry, and report delivery status (and delivery status should take retry into consideration). This could leverage metrics API or via a dedicated callback mechanism.

**Comment by david-esteves-sh** [comment] 2023-08-07 10:56
Can anyone comment if there's any plans to do work around this? I was thinking it would be great to chain BatchExportProcessor's and have a layer where I track some metrics(accepted_count, export_count). I would like to have more visibility into throughput and backpressure in my dotnet apps. The opentelemetry-collector exposes a bunch of metrics around the export pipeline and it would be great if we could get something similar in the SDK. `droppedCount` being emit only on shutdown as a log instead of being a guage or something is a bit annoying as I don't realise my app is losing data until I restart it.

**Comment by cijothomas** [comment] 2023-09-06 14:21
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3880 closing as duplicate of this. Agree this is an important issue to be addressed soon, now that 1.6 is out!

**Closed by cijothomas** 2023-09-06 14:21 UTC
Labels: enhancement
