### ISSUE TITLE
Http Headers are shown as custom labels when open telemetry agent is used

### ISSUE THREAD

**Issue by sjrules** [open-telemetry/opentelemetry-dotnet#5591] opened 2024-05-03 11:12 UTC
# Question

Hi ,

When I use open telemetry agent in NET 6 web application to send the trace to data Elastic Server , only few of http headers are shown in metadata of trace , and if any additional header is added using activity.SetTag for the http request , http header are shown as custom labels like labels.http_request_headers , but it Elastic agent is used for the same app all http headers are shown under http section and not as custom labels .

Is there any way to show http header under http section instead as custom labels ?
<img width="720" alt="Capture" src="https://github.com/open-telemetry/opentelemetry-dotnet/assets/57788460/a06a9d35-e322-4166-9625-8d213054ae64">

**Comment by vishweshbankwar** [comment] 2024-05-06 21:15
@sjrules - It looks like your issue is specific to elastic and not related to OpenTelemetry API/SDK? Could you please clarify? 

@stevejgordon - Would you be able to help here?

**Comment by stevejgordon** [comment] 2024-05-07 07:41
Thanks for pinging me, @vishweshbankwar. @sjrules This is an artefact of how we transform OTel data to store it into Elastic APM. Any unmapped attributes are currently stored as labels. We are working on improving this, but in this case, I think we should be able to map this data to our Elastic format for storage and a better experience. We have an [OTel distro](https://www.nuget.org/packages/Elastic.OpenTelemetry/1.0.0-alpha.3) where we can make this happen very quickly, and then we can review fixing the intact mappings as well.

**Comment by sjrules** [comment] 2024-05-07 11:06
@stevejgordon Thanks for the reply . I am using Open Telemetry Agent for instrumenting AspNet Application .  And I was trying to add http headers under http section of elastic metadata . 

Right now I am just using current activity to SetTag for the http request/response , but this does not seem to be working and headers seem to be coming in custom label section of elastic .

**Comment by stevejgordon** [comment] 2024-05-17 12:31
@sjrules So what happens on the backend for Elastic is we receive OTLP data and map/transform it to the Elastic APM data model. We have a bunch of mappings for the semantic convention attributes, etc. Any custom attributes will be mapped under `labels.*` or `numeric_labels.*`. So what you're seeing is the expected behaviour.

**Comment by stevejgordon** [comment] 2024-06-05 07:16
@sjrules I discussed this internally on my return from vacation, and we agree that `http.request.header.<key>` and `http.response.header.<key>` attributes should be mapped to our data model. I've [opened an issue](https://github.com/elastic/apm-data/issues/285) to track this.

**Comment by Kielek** [comment] 2024-06-05 07:41
Closing per @stevejgordon comment.

**Closed by Kielek** 2024-06-05 07:41 UTC
Labels: question
