### ISSUE TITLE
Not found OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule package from nuget

### ISSUE THREAD

**Issue by carldai0106** [open-telemetry/opentelemetry-dotnet#2318] opened 2021-09-08 08:12 UTC
# Feature Request

I am using .net framework 4.6.2 and Asp.net WebApi and integrate OpenTelemetry;
When I run my webapi to get a error; OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule  dll is missing.
Then I want to get OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule package from nuget, but it is not exists on nuget.

**Comment by cijothomas** [comment] 2021-09-08 13:30
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2259#issuecomment-905917754

**Comment by cijothomas** [comment] 2021-09-08 13:30
Duplicate of @2259

**Closed by cijothomas** 2021-09-08 13:30 UTC
Labels: enhancement
